const formioURL = 'https://test-d.detozgnrw.mms-at-work.de/formio/form'
const lucomURL = 'https://test-d.detozgnrw.mms-at-work.de/fms/service/portal/v1/system/info'
const zufiURL = 'https://zufi.api.vsm.nrw/health'
const leikaURL = 'https://leika.vsm.nrw/health'
const agsURL1 = 'https://ags-ars.api.vsm.nrw/orte?suchbegriff=D%C3%BCs'
const websucheURL = 'https://web-suche.api.vsm.nrw/web-treffer?suchbegriff=Perso'
