const Services = [{
        name: 'FMS - Form.io',
        url: 'https://test-d.detozgnrw.mms-at-work.de/formio/form',
        status: '',
        icon: '',
        options: '',
    },
    {
        name: 'FMS - Lucom',
        url: 'https://test-d.detozgnrw.mms-at-work.de/fms/service/portal/v1/system/info',
        status: '',
        icon: '',
        options: '',
    },
    {
        name: 'VSM - LeiKa',
        url: 'https://leika.vsm.nrw/health',
        status: '',
        icon: '',
        options: '',
    },
    {
        name: 'VSM - ZuFi',
        url: 'https://zufi.api.vsm.nrw/health',
        status: '',
        icon: '',
        options: '',
    },
    {
        name: 'VSM - WebSuche',
        url: 'https://web-suche.api.vsm.nrw/web-treffer?suchbegriff=Perso',
        status: '',
        icon: '',
        options: '',
    },
    {
        name: 'VSM - AGS',
        url: 'https://ags-ars.api.vsm.nrw/orte?suchbegriff=D%C3%BCs',
        status: '',
        icon: '',
        options: '',
    },
    /* {
        name: 'ZSP',
        url: '',
        status: '',
        icon: '',
        options: '',
    },
    {
        name: 'ServiceKonto',
        url: 'https://sknrwq.krzn.de/AutentIDConnect/sk/.well-known/openid-configuration',
        status: '',
        icon: '',
        options: '',
    },
    {
        name: 'ZDI - Datenaustauschdienst',
        url: '',
        status: '',
        icon: '',
        options: '',
    },
    {
        name: 'ePayBL',
        url: '',
        status: '',
        icon: '',
        options: '',
    } */
]